name: flutter_bili_talk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 组件化配置
  hi_net:
    path: ./component/hi_net

  hi_barrage:
    path: ./component/hi_barrage


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^3.1.0 #1. json 解析 注解器
  shared_preferences: '>=0.5.7 <2.0.8' #本地存储
  fluttertoast: ^7.1.6
  underline_indicator: ^0.0.2 # 首页顶部指示器
  flutter_swiper: ^1.1.6
  flutter_aes_ecb_pkcs5: ^0.1.1 # AES_ECB加密解密
  flutter_nested: ^1.0.0 # 帧率优化插件
  flutter_statusbar_manager: ^2.0.0 # 状态栏管理
  flutter_staggered_grid_view: ^0.3.3 # 瀑布流多样式
  intl: ^0.17.0
  transparent_image: ^1.0.0
  cached_network_image: ^2.5.0 # 图片缓存框架
  chewie: ^1.2.2 # 视频播放器
  video_player: ^2.1.10 # 官方播放器
  orientation: ^1.3.0
  url_launcher: ^5.7.10 #打开第三方app的插件
  clipboard: ^0.1.2+8 #剪贴板
  flutter_overlay: ^1.0.0 # 发送弹幕软键盘适配
  provider: ^5.0.0  # 状态管理

#解决依赖冲突，强制覆写为同一个版本
#dependency_overrides:
#  archive:3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:  # 集成测试
    sdk: flutter

  json_serializable: ^3.5.0 #2.json 解析
  build_runner: ^1.0.0 #3.json 解析

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/  # 会自动加载该目录下的资源到包里

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
